### ISSUE TITLE
Cannot run xiblint

### ISSUE THREAD

**Issue by bpoplauschi** [lyft/xiblint#57]
Hi there,

I would like to try `xiblint` (sounds like a nice tool), but I could not get it to run.

I keep getting this error:
```
Traceback (most recent call last):
  File "/Users/bogdanp/.pyenv/versions/3.6.10/bin/xiblint", line 8, in <module>
    sys.exit(main())
  File "/Users/bogdanp/.pyenv/versions/3.6.10/lib/python3.6/site-packages/xiblint/__main__.py", line 27, in main
    from patch_element_tree import patch_element_tree
ModuleNotFoundError: No module named 'patch_element_tree'
```

I tried running it with python 2, 3.6 and even 3.7, same error.
I tried installing via pip or even cloning locally the git repo + `python setup.py install`, same error.

Can you assist me, please?

My current environment:
```
MacOS Catalina 10.15.4
Xcode 11.3.1
pyenv 1.2.18
python 3.6.10
pip 20.0.2
xiblint 0.9.14
```

I see the `patch_element_tree.py` is there on disk, but apparently it's not getting imported.
```
ls ~/.pyenv/versions/3.6.10/lib/python3.6/site-packages/xiblint/
__init__.py
__main__.py
__pycache__
config.py
patch_element_tree.py
rules
xibcontext.py
xibutils.py
xmlutils.py
```

**Comment by bpoplauschi** [comment]
Appreciate it @ikonst  - seems like you fixed the issue :)

**Comment by bpoplauschi** [comment]
I confirm the latest version (0.9.15) works with Python 3.6. Closing
